### ISSUE TITLE
Syntax error on NdX-C expressions

### ISSUE THREAD

**Issue by mindbound** [matteocorti/roll#9]
The latest version (2.4.0) on Arch Linux throws a syntax error when using expressions of the form `NdX-C`, e.g., `2d6-3`, regardless of spaces around the minus sign.

**Comment by matteocorti** [comment]
It's a parser problem introduced with the -L notation.
I'll fix it but at the moment downgrading to 2.1.1 should work

**Comment by mindbound** [comment]
Thanks, I'll downgrade for now.

**Comment by matteocorti** [comment]
Fixed in the new release
